# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='téléphone')),
                ('anniversaire', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
            ],
            options={
                'verbose_name_plural': 'adhérents',
                'verbose_name': 'adhérent',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(choices=[(2015, '2015 - 2016'), (2014, '2014 - 2015'), (2013, '2013 - 2014'), (2012, '2012 - 2013'), (2011, '2011 - 2012'), (2010, '2010 - 2011'), (2009, '2009 - 2010'), (2008, '2008 - 2009'), (2007, '2007 - 2008'), (2006, '2006 - 2007'), (2005, '2005 - 2006'), (2004, '2004 - 2005'), (2003, '2003 - 2004'), (2002, '2002 - 2003'), (2001, '2001 - 2002'), (2000, '2000 - 2001'), (1999, '1999 - 2000'), (1998, '1998 - 1999'), (1997, '1997 - 1998'), (1996, '1996 - 1997'), (1995, '1995 - 1996'), (1994, '1994 - 1995'), (1993, '1993 - 1994'), (1992, '1992 - 1993'), (1991, '1991 - 1992'), (1990, '1990 - 1991'), (1989, '1989 - 1990'), (1988, '1988 - 1989')], default=2015, verbose_name='année')),
                ('paiement', models.CharField(choices=[('attente', 'En attente de paiement...'), ('cheque', 'Chèque'), ('especes', 'Espèces')], default='attente', max_length=10, verbose_name='paiement')),
                ('certificat', models.BooleanField(default=False, verbose_name='certificat médical')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('adherent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertigo.Adherent')),
            ],
            options={
                'verbose_name_plural': 'adhésions',
                'verbose_name': 'adhésion',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(help_text='Au format international, ex: +33434170166', max_length=128, verbose_name='téléphone')),
                ('adherent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertigo.Adherent')),
            ],
            options={
                'verbose_name_plural': "contacts en cas d'urgence",
                'verbose_name': "contact en cas d'urgence",
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now, verbose_name="date d'emprunt")),
                ('adherent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertigo.Adherent')),
            ],
            options={
                'verbose_name_plural': 'emprunts',
                'verbose_name': 'emprunt',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('identifiant', models.IntegerField(blank=True, verbose_name='identifiant')),
                ('remarque', models.TextField(blank=True, verbose_name='remarques')),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('normal', 'Normal'), ('especes', 'A surveiller !'), ('reforme', 'Réformé')], default='normal', max_length=10, verbose_name='etat')),
                ('date_achat', models.DateField(blank=True, null=True, verbose_name="date d'achat")),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='marque')),
                ('modele', models.CharField(blank=True, max_length=100, verbose_name='modèle')),
                ('couleur', models.CharField(blank=True, max_length=100, verbose_name='couleur')),
                ('magasin', models.CharField(blank=True, max_length=100, verbose_name='magasin')),
                ('num_serie', models.CharField(blank=True, max_length=100, verbose_name='numéro de série')),
                ('date_fabrication', models.DateField(blank=True, null=True, verbose_name='date de fabrication')),
            ],
            options={
                'verbose_name_plural': 'fiches matériel',
                'verbose_name': 'fiche matériel',
            },
        ),
        migrations.AddField(
            model_name='emprunt',
            name='materiel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vertigo.Materiel'),
        ),
    ]
