# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vertigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='remarque',
            field=models.CharField(blank=True, max_length=250, verbose_name='remarques'),
        ),
    ]
