# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vertigo', '0002_auto_20151211_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiel',
            options={'ordering': ['identifiant'], 'verbose_name': 'fiche matériel', 'verbose_name_plural': 'fiches matériel'},
        ),
    ]
